### ISSUE TITLE
.dylib not properly linked

### ISSUE THREAD

**Issue by thefangbear** [Roobotics-FRC/RooSight#1]
It seems to me that it is a linking issue. Everything works just fine when I keep the .dylib file at its installed location (by brew), but everything breaks when I move the exact same .dylib file to RooSight folder despite I have the same folder structures setup

**Comment by thefangbear** [comment]
Revised folder structure (attempted):
```
.
├── LICENSE
├── README.md
├── build
...blablablablabla
├── build.gradle
├── gradle
│   └── wrapper
│       ├── gradle-wrapper.jar
│       └── gradle-wrapper.properties
├── gradlew
├── gradlew.bat
├── include
│   ├── opencv
......stuffs
├── lib
│   ├── libopencv_calib3d.3.2.0.dylib
...blablabla
├── settings.gradle
├── share
│   └── OpenCV
│       └── java
│           ├── libopencv_java320.dylib
│           └── opencv-320.jar
└── src
...blablablablabla
        └── main.iml

54 directories, 289 files
```

**Comment by thefangbear** [comment]
Result with `libopencv_java320.dylib` at default location where brew installed it to:
```
:compileJava
:processResources UP-TO-DATE
:classes
:run
Loaded library.
voila!

BUILD SUCCESSFUL

Total time: 1.574 secs
```

Result with `libopencv_java320.dylib` being moved to `RooSight/share/OpenCV/java/`:
```
:compileJava
:processResources UP-TO-DATE
:classes
:run
Loaded library.
java.lang.UnsatisfiedLinkError: org.opencv.imgcodecs.Imgcodecs.imread_1(Ljava/lang/String;)J
        at org.opencv.imgcodecs.Imgcodecs.imread_1(Native Method)
        at org.opencv.imgcodecs.Imgcodecs.imread(Imgcodecs.java:118)
        at com.nottesla.roosight.Test.main(Test.java:19)
voila!

BUILD SUCCESSFUL

Total time: 1.144 secs
```
Notice the exception caught in the second one.

**Comment by thefangbear** [comment]
@aaplmath

**Comment by thefangbear** [comment]
I guess it might be a runtime search path issue (output of `otool -L`)
```
libopencv_java320.dylib:
	@rpath/libopencv_core.3.2.dylib (compatibility version 3.2.0, current version 3.2.0)
	/System/Library/Frameworks/OpenCL.framework/Versions/A/OpenCL (compatibility version 1.0.0, current version 1.0.0)
	/System/Library/Frameworks/Accelerate.framework/Versions/A/Accelerate (compatibility version 1.0.0, current version 4.0.0)
	/usr/lib/libc++.1.dylib (compatibility version 1.0.0, current version 307.4.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1238.0.0)
```

**Comment by thefangbear** [comment]
Figured it out. It is a linker problem. The old `libopencv_java320.dylib` probably wasn't properly compiled. By re-copying over the `libopencv_java320.dylib` compiled by brew we get some new rpath-es:
```
libopencv_java320.dylib:
	/usr/local/opt/opencv3/share/OpenCV/java/libopencv_java320.dylib (compatibility version 0.0.0, current version 0.0.0)
	@rpath/libopencv_photo.3.2.dylib (compatibility version 3.2.0, current version 3.2.0)
	@rpath/libopencv_video.3.2.dylib (compatibility version 3.2.0, current version 3.2.0)
	@rpath/libopencv_objdetect.3.2.dylib (compatibility version 3.2.0, current version 3.2.0)
	@rpath/libopencv_calib3d.3.2.dylib (compatibility version 3.2.0, current version 3.2.0)
	/System/Library/Frameworks/Accelerate.framework/Versions/A/Accelerate (compatibility version 1.0.0, current version 4.0.0)
	@rpath/libopencv_features2d.3.2.dylib (compatibility version 3.2.0, current version 3.2.0)
	@rpath/libopencv_flann.3.2.dylib (compatibility version 3.2.0, current version 3.2.0)
	@rpath/libopencv_ml.3.2.dylib (compatibility version 3.2.0, current version 3.2.0)
	@rpath/libopencv_highgui.3.2.dylib (compatibility version 3.2.0, current version 3.2.0)
	@rpath/libopencv_videoio.3.2.dylib (compatibility version 3.2.0, current version 3.2.0)
	@rpath/libopencv_imgcodecs.3.2.dylib (compatibility version 3.2.0, current version 3.2.0)
	@rpath/libopencv_imgproc.3.2.dylib (compatibility version 3.2.0, current version 3.2.0)
	@rpath/libopencv_core.3.2.dylib (compatibility version 3.2.0, current version 3.2.0)
	/usr/lib/libc++.1.dylib (compatibility version 1.0.0, current version 120.1.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1226.10.1)
```

I guess I'll submit a PR to fix this issue.

**Comment by thefangbear** [comment]
Solved since https://github.com/Roobotics-FRC/RooSight/commit/d8759fed39b5a4e7bf32687021657c8919a99d23.
